#######################################################################
# File name : docker-compose.yml
# Author : Olivier Galand (31/12/2021)
# Author email : galand.olivier.david@gmail.com
# Project : CashFactory
# Project repository : https://github.com/OlivierGaland/CashFactory
# 
# Docker-compose file of CashFactory
#######################################################################
version: '3.5'

services:
    #Start of Portainer + Webserver section :
    # Web GUI with quicklinks to apps dashboards and help : connect to your device port 80 (Webserver)
    # Container management and monitoring : connect to your device port 9000 (Portainer)
    Webserver:
        image: fnichol/uhttpd
        volumes:
            - ./www:/www
        ports:
            - 80:80
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.10
    Portainer:
        image: portainer/portainer-ce:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - 8000:8000
            - 9000:9000
            - 9443:9443
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.11
    #End of Portainer + Webserver section

    #Start of Earnapp section (remove this if Earnapp not wanted)
    # variables to define in .env file :
    # EARNAPP_DEVICE_ID : Your node id : sdk-node-<md5sum>
    #                     <md5sum> is a 32 char string containing a-z and 0-9 range : 
    #                       ex : Easy way to generate one :  echo "random string" | md5sum 
    #                            This will print 9f33ffbb8a9dcedb28ea909775a6b0d3  -
    #                            In that case use : sdk-node-9f33ffbb8a9dcedb28ea909775a6b0d3
    Earnapp:
        depends_on:
            - Portainer
            - Webserver
        image: madereddy/earnapp:latest
        volumes:
            - earnapp-data:/etc/earnapp
        restart: always
        environment:
            - EARNAPP_UUID=$EARNAPP_DEVICE_ID
        networks:
            default:
                ipv4_address: 172.106.0.20
    #End of Earnapp section


    #Start of HoneyGain section (remove this if HoneyGain not wanted)
    # variables to define in .env file :
    # HONEYGAIN_EMAIL : Your Honeygain account email
    # HONEYGAIN_PASSWD : Your Honeygain account password 
    # DEVICE_NAME : This computer name (for display on dashboard)
    Honeygain:
        depends_on:
            - Portainer
            - Webserver
        image: honeygain/honeygain
        command: -tou-accept -email $HONEYGAIN_EMAIL -pass '$HONEYGAIN_PASSWD' -device $DEVICE_NAME
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.30
    #End of HoneyGain section

    #Start of IproyalPawns section (remove this if IproyalPawns not wanted)
    # variables to define in .env file :
    # IPROYALPAWNS_EMAIL : Your IproyalPawns account email
    # IPROYALPAWNS_PASSWD : Your IproyalPawns account password 
    # DEVICE_NAME : This computer name (for display on dashboard)
    IproyalPawns:
        depends_on:
            - Portainer
            - Webserver
        image: iproyal/pawns-cli:latest
        command: -email=$IPROYALPAWNS_EMAIL -password='$IPROYALPAWNS_PASSWD' -device-name=$DEVICE_NAME -accept-tos
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.40
    #End of IproyalPawns section

    #Start of Peer2profit section (remove this if Peer2profit not wanted)
    # variables to define in .env file :
    # PEER2PROFIT_EMAIL : Your Peer2profit account email
    Peer2profit:
        depends_on:
            - Portainer
            - Webserver
        image: enwaiax/peer2profit:latest
        restart: always
        environment:
            - email=$PEER2PROFIT_EMAIL
            - use_proxy=false
        networks:
            default:
                ipv4_address: 172.106.0.50
    #End of Peer2profit section

    #Start of Packetstream section (remove this if Packetstream not wanted)
    # variables to define in .env file :
    # PACKETSTREAM_CID : Your Packetstream CID (available in packetstream dashboard)
    Packetstream_PsClient:
        depends_on:
            - Portainer
            - Webserver
        image: packetstream/psclient:latest
        restart: always
        environment:
            - CID=$PACKETSTREAM_CID
        networks:
            default:
                ipv4_address: 172.106.0.60
    Packetstream_Watchtower:
        depends_on:
            - Portainer
            - Webserver
            - Packetstream_PsClient
        image: containrrr/watchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 --scope PacketStream ${_COMPOSE_PROJECT_NAME}_Packetstream_PsClient_${_COMPOSE_PROJECT_STACK_ID}
        labels:
            - com.centurylinklabs.watchtower.scope=PacketStream
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.61
    #End of Packetstream section
    
    #Start of Bitping section (remove this if Bitping not wanted)
    Bitping:
        depends_on:
            - Portainer
            - Webserver
        image: bitping/bitping-node:latest
        restart: always
        volumes:
            - ./data/bitping:/root/.bitping
        networks:
            default:
                ipv4_address: 172.106.0.70
    #End of Bitping section     

    #Start of TraffMonetizer section (remove this if TraffMonetizer not wanted)
    # variables to define in .env file :
    # TRAFFMONETIZER_TOKEN : Your application token (available in TraffMonetizer dashboard)
    TraffMonetizer:
        depends_on:
            - Portainer
            - Webserver
        image: traffmonetizer/cli_v2:latest
        restart: always
        command: start accept --token ${TRAFFMONETIZER_TOKEN}
        networks:
            default:
                ipv4_address: 172.106.0.80
    #End of Packetstream section   
    
    #Start of Repocket section (remove this if Repocket not wanted)
    # variables to define in .env file :
    # RP_EMAIL : Your application mail 
    # RP_API_KEY : Your application api key (available in repocket dashboard)
    Repocket:
        depends_on:
            - Portainer
            - Webserver
        image: repocket/repocket:latest
        restart: always
        environment:
          - RP_EMAIL
          - RP_API_KEY
        networks:
            default:
                ipv4_address: 172.106.0.90
    #End of Repocket section    

    #Start of Proxylite section (remove this if Proxylite not wanted)
    # variables to define in .env file :
    # PROXYLITE_USER_ID : Your application use id (available in proxylite dashboard)
    Proxylite:
        depends_on:
            - Portainer
            - Webserver
        image: proxylite/proxyservice:latest
        restart: always
        environment:
          - USER_ID=$PROXYLITE_USER_ID
        networks:
            default:
                ipv4_address: 172.106.0.100
    #End of Proxylite section 

    #Start of Proxyrack section (remove this if Proxyrack not wanted)
    # variables to define in .env file :
    # PROXYRACK_HOST_UUID : Your host UUID (random string), you can generate it using the command : cat /dev/urandom | LC_ALL=C tr -dc 'A-F0-9' | dd bs=1 count=64 2>/dev/null
    Proxyrack:
        depends_on:
            - Portainer
            - Webserver
        image: proxyrack/pop:latest
        restart: always
        environment:
          - UUID=$PROXYRACK_HOST_UUID
        networks:
            default:
                ipv4_address: 172.106.0.110
    #End of Proxyrack section 


    #Start of Cloudcollab section (remove if not wanted) => currently under evaluation by dev, seems not working well
    # Cloudcollab:
    #     depends_on:
    #         - Portainer
    #         - Webserver
    #     image: cloudcollabapp/peer:latest
    #     restart: always
    #     networks:
    #         default:
    #             ipv4_address: 172.106.0.120
    #End of Cloudcollab section

    #Start of EarnFm section (remove this if EarnFm not wanted)
    # variables to define in .env file :
    # EARNFM_APIKEY : Your API key (available in earnfm dashboard -> more)
    EarnFm_Client:
        depends_on:
            - Portainer
            - Webserver
        image: earnfm/earnfm-client:latest
        restart: always
        environment:
            - EARNFM_TOKEN=$EARNFM_APIKEY
        networks:
            default:
                ipv4_address: 172.106.0.130
    EarnFm_Watchtower:
        depends_on:
            - Portainer
            - Webserver
            - EarnFm_Client
        image: containrrr/watchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 --scope EarnFm ${_COMPOSE_PROJECT_NAME}_EarnFm_Client_${_COMPOSE_PROJECT_STACK_ID}
        labels:
            - com.centurylinklabs.watchtower.scope=EarnFm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.131
    #End of EarnFm section


volumes:
    portainer_data:
    earnapp-data:

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
